# 04_SES_Feature_Engineering_Final
Production-grade SES Feature Engineering Pipeline

In [1]:
import pandas as pd
import numpy as np
from collections import Counter
from sklearn.preprocessing import MinMaxScaler

pd.set_option("display.max_columns",None)

In [2]:
job_skills = pd.read_csv("job_skills.csv")
job_skills_map = pd.read_csv("job_skills_1.csv")
skills_map = pd.read_csv("skills_1.csv")

job_industries = pd.read_csv("job_industries.csv")
industries = pd.read_csv("industries.csv")

linkedin = pd.read_csv("linkedin_job_postings.csv")

postings = pd.read_csv("postings.csv")

salaries = pd.read_csv("salaries.csv")

stack = pd.read_csv(
    "survey_results_public.csv",
    low_memory=False
)

In [3]:
SOFT_SKILLS = [
    "communication",
    "communication skills",
    "teamwork",
    "leadership",
    "customer service",
    "problem solving",
    "problemsolving",
    "collaboration",
    "attention to detail",
    "management",
    "sales",
    "training"
]

In [4]:
all_skills = []

for row in job_skills["job_skills"].dropna():

    skills_list = str(row).split(",")

    all_skills.extend(
        [x.strip().lower() for x in skills_list]
    )

demand_df = (
    pd.Series(all_skills)
    .value_counts()
    .reset_index()
)

demand_df.columns = [
    "skill",
    "linkedin_demand"
]

demand_df = demand_df[
    ~demand_df["skill"].isin(SOFT_SKILLS)
]

demand_df.head(20)

                     skill  linkedin_demand
6          time management           142911
9       project management           121563
10    interpersonal skills           100267
11            patient care            99926
13                 nursing            88015
16           data analysis            81964
17  microsoft office suite            75531
18   organizational skills            75274
19    inventory management            71911
20     high school diploma            67267
21              scheduling            64461
22       bachelor's degree            63490
23            multitasking            62044
24       analytical skills            60768
25        microsoft office            60604
26            adaptability            59121
27             flexibility            56896
28       critical thinking            53081
29           documentation            51875
30            organization            47045

In [5]:
skill_lookup = (
    job_skills_map
    .merge(
        skills_map,
        on="skill_abr",
        how="left"
    )
)

skill_lookup["skill_name"] = (
    skill_lookup["skill_name"]
    .str.lower()
)

skill_lookup.head()

       job_id skill_abr        skill_name
0  3884428798      MRKT         marketing
1  3884428798        PR  public relations
2  3884428798       WRT   writing/editing
3  3887473071      SALE             sales
4  3887465684       FIN           finance

In [6]:
industry_skill = (
    skill_lookup
    .merge(
        job_industries,
        on="job_id",
        how="left"
    )
)

industry_adoption = (
    industry_skill
    .groupby("skill_name")["industry_id"]
    .nunique()
    .reset_index()
)

industry_adoption.columns = [
    "skill",
    "industry_adoption"
]

industry_adoption.head()

                 skill  industry_adoption
0  accounting/auditing                260
1       administrative                263
2          advertising                116
3              analyst                223
4         art/creative                180

In [7]:
country_counts = (
    linkedin["search_country"]
    .value_counts()
)

geo_score = pd.DataFrame({
    "skill": demand_df["skill"],
    "geographic_spread":
    len(country_counts)
})

geo_score.head()

                   skill  geographic_spread
6        time management                  4
9     project management                  4
10  interpersonal skills                  4
11          patient care                  4
13               nursing                  4

In [8]:
salary_jobs = (
    salaries
    .merge(
        job_skills_map,
        on="job_id",
        how="inner"
    )
    .merge(
        skills_map,
        on="skill_abr",
        how="left"
    )
)

salary_jobs["skill_name"] = (
    salary_jobs["skill_name"]
    .str.lower()
)

salary_jobs["salary_score"] = (
    salary_jobs["max_salary"]
    .fillna(0)
    +
    salary_jobs["min_salary"]
    .fillna(0)
) / 2

salary_feature = (
    salary_jobs
    .groupby("skill_name")["salary_score"]
    .mean()
    .reset_index()
)

salary_feature.columns = [
    "skill",
    "salary_premium"
]

salary_feature.head()

                 skill  salary_premium
0  accounting/auditing    79443.734424
1       administrative    36685.346739
2          advertising    89163.334432
3              analyst    65816.099677
4         art/creative    65044.877505

In [9]:
from collections import Counter

def extract_counts(series):

    counter = Counter()

    for row in series.dropna():

        for item in str(row).split(";"):

            counter[
                item.strip().lower()
            ] += 1

    return counter

In [10]:
current_usage = Counter()

usage_cols = [

    "LanguageHaveWorkedWith",

    "DatabaseHaveWorkedWith",

    "PlatformHaveWorkedWith",

    "WebframeHaveWorkedWith",

    "ToolsTechHaveWorkedWith",

    "MiscTechHaveWorkedWith"
]

for col in usage_cols:

    current_usage.update(
        extract_counts(stack[col])
    )

current_usage_df = pd.DataFrame(
    current_usage.items(),
    columns=[
        "skill",
        "current_usage"
    ]
)

current_usage_df.head()

                     skill  current_usage
0  bash/shell (all shells)          20412
1                       go           8103
2                 html/css          31816
3                     java          18239
4               javascript          37492

In [11]:
future_interest = Counter()

future_cols = [

    "LanguageWantToWorkWith",

    "DatabaseWantToWorkWith",

    "PlatformWantToWorkWith",

    "WebframeWantToWorkWith",

    "ToolsTechWantToWorkWith",

    "MiscTechWantToWorkWith"
]

for col in future_cols:

    future_interest.update(
        extract_counts(stack[col])
    )

future_interest_df = pd.DataFrame(
    future_interest.items(),
    columns=[
        "skill",
        "future_interest"
    ]
)

future_interest_df.head()

                     skill  future_interest
0  bash/shell (all shells)            13744
1                       go            13837
2                 html/css            20721
3                     java            10668
4               javascript            23774

In [18]:
master = demand_df.copy()

master = master.merge(
    industry_adoption,
    on="skill",
    how="left"
)

master = master.merge(
    geo_score,
    on="skill",
    how="left"
)

master = master.merge(
    salary_feature,
    on="skill",
    how="left"
)

master = master.merge(
    current_usage_df,
    on="skill",
    how="left"
)

master = master.merge(
    future_interest_df,
    on="skill",
    how="left"
)

master.fillna(0,inplace=True)

master.head(1000)

,skill,linkedin_demand,industry_adoption,geographic_spread,salary_premium,current_usage,future_interest
0,time management,142911,0.0,4,0.000000,0.0,0.0
1,project management,121563,252.0,4,92119.521639,0.0,0.0
2,interpersonal skills,100267,0.0,4,0.000000,0.0,0.0
3,patient care,99926,0.0,4,0.000000,0.0,0.0
4,nursing,88015,0.0,4,0.000000,0.0,0.0
...,...,...,...,...,...,...,...
995,cash management,2722,0.0,4,0.000000,0.0,0.0
996,policy compliance,2720,0.0,4,0.000000,0.0,0.0
997,guidance,2717,0.0,4,0.000000,0.0,0.0
998,computers,2712,0.0,4,0.000000,0.0,0.0
999,crossselling,2709,0.0,4,0.000000,0.0,0.0

In [13]:
features = [

    "linkedin_demand",

    "industry_adoption",

    "geographic_spread",

    "salary_premium",

    "current_usage",

    "future_interest"
]

scaler = MinMaxScaler()

master[features] = scaler.fit_transform(
    master[features]
)

In [14]:
master["future_score"] = (

    0.30 * master["future_interest"]

    +

    0.25 * master["linkedin_demand"]

    +

    0.15 * master["current_usage"]

    +

    0.15 * master["industry_adoption"]

    +

    0.10 * master["geographic_spread"]

    +

    0.05 * master["salary_premium"]

)

master.head()

,skill,linkedin_demand,industry_adoption,geographic_spread,salary_premium,current_usage,future_interest,future_score
0,time management,1.000000,0.0,0.0,0.000000,0.0,0.0,0.250000
1,project management,0.850619,0.8,0.0,0.663176,0.0,0.0,0.365814
2,interpersonal skills,0.701602,0.0,0.0,0.000000,0.0,0.0,0.175401
3,patient care,0.699216,0.0,0.0,0.000000,0.0,0.0,0.174804
4,nursing,0.615870,0.0,0.0,0.000000,0.0,0.0,0.153968

In [15]:
master.sort_values(
    "future_score",
    ascending=False
).head(50)

,skill,linkedin_demand,industry_adoption,geographic_spread,salary_premium,current_usage,future_interest,future_score
71,python,0.176104,0.000000,0.0,0.000000,0.819348,0.953735,0.453049
249,javascript,0.066126,0.000000,0.0,0.000000,1.000000,0.905262,0.438110
409,docker,0.043755,0.000000,0.0,0.000000,0.779340,1.000000,0.427840
85,sql,0.154181,0.000000,0.0,0.000000,0.818361,0.852943,0.417182
1693,postgresql,0.011287,0.000000,0.0,0.000000,0.681105,0.914058,0.379205
1,project management,0.850619,0.800000,0.0,0.663176,0.000000,0.000000,0.365814
3138,html/css,0.005745,0.000000,0.0,0.000000,0.848608,0.789011,0.365431
839,typescript,0.022378,0.000000,0.0,0.000000,0.617465,0.770657,0.329411
13081,npm,0.001218,0.000000,0.0,0.000000,0.716580,0.636433,0.298721
6789,amazon web services (aws),0.002533,0.000000,0.0,0.000000,0.591886,0.686924,0.295493
733,react,0.025464,0.000000,0.0,0.000000,0.511229,0.586551,0.259016
1191,node.js,0.015954,0.000000,0.0,0.000000,0.527366,0.561077,0.251416
0,time management,1.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.250000
1166,mysql,0.016304,0.000000,0.0,0.000000,0.562760,0.467177,0.228643
4520,rust,0.003905,0.000000,0.0,0.000000,0.201616,0.656157,0.228066
70,business development,0.177048,0.996825,0.0,0.602850,0.000000,0.000000,0.223928
38995,sqlite,0.000336,0.000000,0.0,0.000000,0.463165,0.513632,0.223648
57,engineering,0.200721,0.907937,0.0,0.715214,0.000000,0.000000,0.222131
575,c#,0.033042,0.000000,0.0,0.000000,0.435240,0.492004,0.221147
167,java,0.097194,0.000000,0.0,0.000000,0.486477,0.406214,0.219134
54,marketing,0.207144,0.765079,0.0,1.000000,0.000000,0.000000,0.216548
383,kubernetes,0.046953,0.000000,0.0,0.000000,0.280140,0.502513,0.204513
20290,pip,0.000735,0.000000,0.0,0.000000,0.468393,0.433821,0.200589
753,go,0.024778,0.000000,0.0,0.000000,0.216126,0.526883,0.196678
384,c++,0.046554,0.000000,0.0,0.000000,0.368799,0.414020,0.191164
642,information technology,0.028787,1.000000,0.0,0.602408,0.000000,0.000000,0.187317
114,finance,0.124589,0.819048,0.0,0.605829,0.000000,0.000000,0.184296
1790,mongodb,0.010664,0.000000,0.0,0.000000,0.346927,0.418171,0.180156
35,quality assurance,0.253852,0.612698,0.0,0.423180,0.000000,0.000000,0.176527
133,manufacturing,0.114093,0.901587,0.0,0.241835,0.000000,0.000000,0.175853
2,interpersonal skills,0.701602,0.000000,0.0,0.000000,0.000000,0.000000,0.175401
3,patient care,0.699216,0.000000,0.0,0.000000,0.000000,0.000000,0.174804
1420,microsoft azure,0.013470,0.000000,0.0,0.000000,0.342740,0.392354,0.172485
41,research,0.241523,0.533333,0.0,0.581645,0.000000,0.000000,0.169463
2996,redis,0.006025,0.000000,0.0,0.000000,0.279073,0.413030,0.167276
2285,google cloud,0.008026,0.000000,0.0,0.000000,0.309533,0.372097,0.160065
31273,vite,0.000441,0.000000,0.0,0.000000,0.288168,0.380017,0.157340
4,nursing,0.615870,0.000000,0.0,0.000000,0.000000,0.000000,0.153968
815781,accounting/auditing,0.000007,0.825397,0.0,0.571922,0.000000,0.000000,0.152407
195,human resources,0.082849,0.685714,0.0,0.529758,0.000000,0.000000,0.150057
1560342,homebrew,0.000000,0.000000,0.0,0.000000,0.322229,0.335009,0.148837
218,design,0.076027,0.695238,0.0,0.489632,0.000000,0.000000,0.147774
186055,other,0.000049,0.879365,0.0,0.304733,0.000000,0.000000,0.147154
1433,c,0.013365,0.000000,0.0,0.000000,0.324976,0.315094,0.146616
3230,microsoft sql server,0.005584,0.000000,0.0,0.000000,0.354076,0.301005,0.144809
5,data analysis,0.573529,0.000000,0.0,0.000000,0.000000,0.000000,0.143382
2448119,strategy/planning,0.000000,0.676190,0.0,0.798038,0.000000,0.000000,0.141330
1937,administrative,0.009754,0.834921,0.0,0.264101,0.000000,0.000000,0.140882
618,product management,0.030390,0.565079,0.0,0.925660,0.000000,0.000000,0.138642
14913,next.js,0.001050,0.000000,0.0,0.000000,0.231543,0.323928,0.132172

In [16]:
master.to_csv(
    "master_skill_dataset.csv",
    index=False
)

print(
    "Saved : master_skill_dataset.csv"
)

Saved : master_skill_dataset.csv